version: '3.7'

services:
  ibm-mq-local:
    restart: always
    build:
      context: .
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    stdin_open: true
    tty: true
